on:
  workflow_call:
    inputs:
      release_version:
        required: true
        type: string
    secrets:
      actions_token:
        required: true
jobs:
  build-push-base-image:
    uses: ./.github/workflows/build-push.yml
    with:
      containerfile: ./Containerfile.workstation
      from_tag: ${{ inputs.release_version }}
      release_version: ${{ inputs.release_version }}
      tag_suffix: -${{ github.ref_name }}
    secrets:
      actions_token: ${{ secrets.actions_token }}
  build-push-nvidia-image:
    uses: ./.github/workflows/build-push.yml
    needs: build-push-base-image
    with:
      containerfile: ./Containerfile.nvidia
      from_tag: ${{ inputs.release_version }}-${{ github.ref_name }}
      release_version: ${{ inputs.release_version }}
      tag_suffix: -nvidia
    secrets:
      actions_token: ${{ secrets.actions_token }}
