name: Build and push ostree containers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 6'
  push:
    branches:
      - "main"
      - "test"
      - "stage"
      - "next"

jobs:
  build-push-images:
    name: Build and push workstation images
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
        release_version:
          - "43"
          - "44"
    uses: ./.github/workflows/build-push-all.yml
    with:
      release_version: ${{ matrix.release_version }}
    secrets:
      actions_token: ${{ secrets.GITHUB_TOKEN }}
