name: Build and push ostree containers
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * 6'
  push:
    branches:
      - 'main'
      - 'test'
      - 'stage'
      - 'next'
jobs:
  build-push-base-image:
    name: Build and push baseline workstation image
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
        release-version:
          - "38"
          - "39"
    uses: ./.github/workflows/build-push-all.yml
    with:
      release-version: ${{ matrix.version }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
